name: check-pr-releasenote

on:
  pull_request:
    types: [opened, reopened, edited, milestoned, demilestoned, labeled, unlabeled, synchronize ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://variantdev/actions:latest
      with:
        args: pullvet -require-any -label releasenote/none -note releasenote
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: variantdev/setup-go-actions@v1
      with:
        go-actions-version: '0.5.0'
    - run: actions pullvet -require-any -label releasenote/none -note releasenote
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
