name: Issue comment command
on:
  # https://help.github.com/en/articles/events-that-trigger-workflows#issue-comment-event-issue_comment
  issue_comment:
    types: [created, edited]

jobs:
  run:
    name: variant
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: variantdev/setup-variant@v1
      with:
        variant-version: '0.36.2' # The Variant version to download (if necessary) and use.
    - name: show variant version
      run: variant version
    - name: run variant
      run: variant --color=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VARIANT_WORKING_DIR: "."
        VARIANT_RUN: ${{ github.event.comment.body }}
        VARIANT_RUN_TRIM_PREFIX: /
        VARIANT_GITHUB_COMMENT: "true"
      if: startsWith(github.event.comment.body, '/')
